### ISSUE TITLE
1.21使用prism会导致报错

### ISSUE THREAD

**Issue by ghost** [Rothes/PrismRefracted#13]
Bug:
在控制台中不断地输出报错:
[Server thread/ERROR]: Could not pass event CreatureSpawnEvent to Prism v3.8.1-CN-b1
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:601) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:588) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_21_R1.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:759) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4286-Spigot-fb8fb72-00fc9fb]
	at org.bukkit.craftbukkit.v1_21_R1.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:678) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4286-Spigot-fb8fb72-00fc9fb]
	at net.minecraft.server.level.WorldServer.addEntity(WorldServer.java:1101) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4286-Spigot-fb8fb72-00fc9fb]
	at net.minecraft.server.level.WorldServer.addFreshEntity(WorldServer.java:1041) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4286-Spigot-fb8fb72-00fc9fb]
	at net.minecraft.world.level.WorldAccess.lambda$addFreshEntityWithPassengers$0(WorldAccess.java:16) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4286-Spigot-fb8fb72-00fc9fb]
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at net.minecraft.world.level.WorldAccess.addFreshEntityWithPassengers(WorldAccess.java:16) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4286-Spigot-fb8fb72-00fc9fb]
	at net.minecraft.world.level.WorldAccess.a_(WorldAccess.java:12) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4286-Spigot-fb8fb72-00fc9fb]
	at net.minecraft.world.entity.npc.MobSpawnerCat.a(SourceFile:98) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4286-Spigot-fb8fb72-00fc9fb]
	at net.minecraft.world.entity.npc.MobSpawnerCat.a(SourceFile:74) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4286-Spigot-fb8fb72-00fc9fb]
	at net.minecraft.world.entity.npc.MobSpawnerCat.a(SourceFile:58) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4286-Spigot-fb8fb72-00fc9fb]
	at net.minecraft.server.level.WorldServer.a(WorldServer.java:504) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4286-Spigot-fb8fb72-00fc9fb]
	at net.minecraft.server.level.ChunkProviderServer.t(ChunkProviderServer.java:423) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4286-Spigot-fb8fb72-00fc9fb]
	at net.minecraft.server.level.ChunkProviderServer.a(ChunkProviderServer.java:352) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4286-Spigot-fb8fb72-00fc9fb]
	at net.minecraft.server.level.WorldServer.a(WorldServer.java:412) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4286-Spigot-fb8fb72-00fc9fb]
	at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:1472) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4286-Spigot-fb8fb72-00fc9fb]
	at net.minecraft.server.dedicated.DedicatedServer.c(DedicatedServer.java:406) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4286-Spigot-fb8fb72-00fc9fb]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1321) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4286-Spigot-fb8fb72-00fc9fb]
	at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1071) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4286-Spigot-fb8fb72-00fc9fb]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4286-Spigot-fb8fb72-00fc9fb]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    network/darkhelmet/prism/actions/entity/CatSerializer.deserializer(Lorg/bukkit/entity/Entity;)V @7: invokestatic
  Reason:
    Type 'org/bukkit/entity/Cat$Type' (current frame, stack[1]) is not assignable to 'java/lang/Enum'
  Current Frame:
    bci: @7
    flags: { }
    locals: { 'network/darkhelmet/prism/actions/entity/CatSerializer', 'org/bukkit/entity/Entity' }
    stack: { 'java/lang/String', 'org/bukkit/entity/Cat$Type' }
  Bytecode:
    0000000: 2ab4 0012 b200 2ab8 0030 c000 074d 2bc0
    0000010: 0009 2cb9 0034 0200 b1                 

	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?]
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3549) ~[?:?]
	at java.base/java.lang.Class.getConstructor0(Class.java:3754) ~[?:?]
	at java.base/java.lang.Class.getConstructor(Class.java:2442) ~[?:?]
	at network.darkhelmet.prism.actions.entity.EntitySerializerFactory.getSerializer(EntitySerializerFactory.java:54) ~[?:?]
	at network.darkhelmet.prism.actions.EntityAction.setEntity(EntityAction.java:53) ~[?:?]
	at network.darkhelmet.prism.actionlibs.ActionFactory.createEntity(ActionFactory.java:243) ~[?:?]
	at network.darkhelmet.prism.actionlibs.ActionFactory.createEntity(ActionFactory.java:258) ~[?:?]
	at network.darkhelmet.prism.actionlibs.ActionFactory.createEntity(ActionFactory.java:227) ~[?:?]
	at network.darkhelmet.prism.listeners.PrismEntityEvents.onCreatureSpawn(PrismEntityEvents.java:523) ~[?:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	... 26 more

复现:
使用Spigot核心在Plugins中加入Prism-CN

控制台截图:
![A578685D733F8D332C242D82A3B3C078](https://github.com/user-attachments/assets/222a98ef-116f-4c94-80c1-e1d6054761df)

**Server (please complete the following information):**
  - Prism Version: Prism v3.8.1-CN-b1
  - Server Type: Spigot
  - Server Version: 1.21

**Additional context**
日志:
[latest.log](https://github.com/user-attachments/files/16576972/latest.log)

**Comment by 8MiYile** [comment]
这个是中文翻译版 只解决语言方面的问题 若有问题 请先使用原版确认是否有该问题 如果原版本身就有这个问题 应该是他那边修复

**Comment by postyizhan** [comment]
try this https://github.com/postyizhan/PrismRefracted
