### ISSUE TITLE
[BUG] Command /pr undo [ID] does not work

### ISSUE THREAD

**Issue by szyha** [Rothes/PrismRefracted#7]
**Describe the bug**
The command "/pr undo [id]" does not work, but "/pr undo last" works. It also seems to me the command "/pr undo", is incorrectly displayed.

**To Reproduce**
1. Type the command "/pr undo [id]"
2. An error message pops up in the chat.

**Expected behavior**
After entering the ID correctly, it should run the command.

**Screenshots**
![javaw_B5eAZrKLWj](https://github.com/Rothes/PrismRefracted/assets/12976368/2510c309-754e-4df0-8b21-64b8d61e0e79)

**Server (please complete the following information):**
  - Prism Version: 3.7.0-CN-b2
  - Server Type: Purpur
  - Server Version: git-Purpur-2004 (MC: 1.20.1)

**Additional context**
The same error also occurs in the English version.
Log from console:
```
[09:59:02] [Server thread/INFO]: szyhownica issued server command: /pr undo 1
[09:59:02] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'pr' in plugin Prism v3.7.0-CN-b2
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1017) ~[purpur-1.20.1.jar:git-Purpur-2004]
	at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[purpur-1.20.1.jar:git-Purpur-2004]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[purpur-1.20.1.jar:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:332) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:316) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2392) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$21(ServerGamePacketListenerImpl.java:2352) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.1.jar:git-Purpur-2004]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1366) ~[purpur-1.20.1.jar:git-Purpur-2004]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.20.1.jar:git-Purpur-2004]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1343) ~[purpur-1.20.1.jar:git-Purpur-2004]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1336) ~[purpur-1.20.1.jar:git-Purpur-2004]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1314) ~[purpur-1.20.1.jar:git-Purpur-2004]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[purpur-1.20.1.jar:git-Purpur-2004]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-2004]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot read field "processType" because "this.actionData" is null
	at network.darkhelmet.prism.actions.PrismProcessAction.getProcessChildActionType(PrismProcessAction.java:55) ~[Prism-3.7.0-CN-b2.jar:?]
	at network.darkhelmet.prism.commands.UndoCommand.handle(UndoCommand.java:73) ~[Prism-3.7.0-CN-b2.jar:?]
	at network.darkhelmet.prism.commandlibs.Executor.onCommand(Executor.java:97) ~[Prism-3.7.0-CN-b2.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	... 23 more
```

**Comment by Rothes** [comment]
Use `/pr lookup r:10 a:prism-process -extended`
The ID used for undo is 
![image](https://github.com/Rothes/PrismRefracted/assets/47097395/d94743ba-eed5-431e-9e4d-0016ee911937)
Will add a check for the issue.

**Comment by Rothes** [comment]
Fixed on https://github.com/Rothes/PrismRefracted/commit/132678e84f4a465e14bd3603cc5002f62c1456ee
